---
# tasks file for base
- name: Install base packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Download RealVNC Server
  block:
    - apt:
        deb: https://www.realvnc.com/download/file/vnc.files/VNC-Server-6.7.2-Linux-x64.deb
    - service:
        name: vncserver-x11-serviced.service
        state: started
        enabled: yes
