---
# tasks file for base
    - name: Install base packages
      apt:
        name: {{ item }}
        state: present
      loop:
        - realvnc-vnc-server
        - vim
        - ssh
        - ntp
